spring:
  application:
    name: rabbitmq-producer-basic
  server:
    port: 8001
  rabbitmq:
    host: localhost
    port: 5692
    username: admin
    password: admin
    order:
      queue: ORDER-QUEUE
      exchange: ORDER-EXCHANGE
      routing-key: ORDER-ROUTING-KEY
      dlq-queue: ORDER-DLQ-QUEUE
      dlq-exchange: ORDER-DLQ-EXCHANGE
      dlq-routing-key: ORDER-DLQ-ROUTING-KEY
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          max-interval: 10s
          multiplier: 1
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5492/postgres
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        default_schema: bulk_db
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 4
        order_updates: true
