insert into po (order_id, created_at) values (1, current_timestamp);
insert into poi (order_item_id, order_id, description, quantity) values (1,1,'Product 001', 322);
insert into poi (order_item_id, order_id, description, quantity) values (2,1,'Product 002', 2);
insert into poi (order_item_id, order_id, description, quantity) values (3,1,'Product 003', 22);
insert into poi (order_item_id, order_id, description, quantity) values (4,1,'Product 004', 42);
insert into poi (order_item_id, order_id, description, quantity) values (5,1,'Product 005', 42);
insert into poi (order_item_id, order_id, description, quantity) values (6,1,'Product 006', 2);
insert into poi (order_item_id, order_id, description, quantity) values (7,1,'Product 007', 45);
insert into poi (order_item_id, order_id, description, quantity) values (8,1,'Product 008', 20);
insert into poi (order_item_id, order_id, description, quantity) values (9,1,'Product 009', 14);
insert into poi (order_item_id, order_id, description, quantity) values (10,1,'Product 0010', 62);
insert into poi (order_item_id, order_id, description, quantity) values (11,1,'Product 0011', 52);
